services:
  db:
    image: postgres:16
    container_name: postgres-db

    env_file:
      - ./backend/.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    image: task-backend
    container_name: backend-container

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: task-frontend
    container_name: frontend-container

    environment:
      VITE_API_URL: "https://9x8f4n18-8000.inc1.devtunnels.ms"
      VITE_GOOGLE_CLIENT_ID: "1057324752424-v3810i4l3fu25cumnoff3avttu35j1lm.apps.googleusercontent.com"

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: